Feature/search house
new-airbnb/kitchen-towel pull request #18
Opened 2019-03-03 04:22 UTC by lyuboxin

Resolves #13, create an index page with google map marker.

2019-03-03 05:46 UTC, xingweitian requested changes

2019-03-03 05:46 UTC, xingweitian commented on addroom.html
> +        var startdate = document.getElementById("date1").value;
bad id

2019-03-03 05:46 UTC, xingweitian commented on addroom.html
> +        var enddate = document.getElementById("date2").value;
bad id

2019-03-03 05:46 UTC, xingweitian commented on addroom.html
>          var postalcode = document.getElementById("code").value;
please be case sensitive.

for example, City, Provinces, Code, Beds...

2019-03-03 05:46 UTC, xingweitian commented on addroom.html
> +        var startdate = document.getElementById("date1").value;
please be more specific.

for example, date_begin, date_end, etc..

2019-03-03 05:46 UTC, xingweitian commented on homepage.html
> +              <input type="date" class="form-control" id="date1" />
the same as above. please try to use a more specific id.

2019-03-03 05:46 UTC, xingweitian commented on homepage.html
> +              <input type="date" class="form-control" id="date2" />
the same as above. please try to use a more specific id.

2019-03-03 05:46 UTC, xingweitian commented on homepage.html
> +        var begindate = document.getElementById("date1").value;
please follow the convention of naming of JavaScript.

this link may be useful: [variable naming principles](https://www.w3cplus.com/javascript/variable-naming-principles.html)

2019-03-03 14:39 UTC, zhangjiangqige commented
Has this been updated to the cs server? The page there doesn't seem to work for me

2019-03-04 03:35 UTC, zhangjiangqige submitted a review, later dismissed
make distance an argument in the future

2019-03-04 03:39 UTC, xingweitian approved these changes

2019-03-04 03:39 UTC, merged