Feature/create detail info page
new-airbnb/kitchen-towel pull request #26
Opened 2019-03-09 18:18 UTC by lyuboxin

Resolved #20 create a page with information of house

2019-03-09 20:44 UTC, zhangjiangqige submitted a review, later dismissed

2019-03-09 20:47 UTC, xingweitian requested changes

2019-03-09 20:47 UTC, xingweitian commented on homepage.html
> +               var detail = "<a href=\"detail.html?home_id="+home_id+"\">details</a>";
please remove the useless blank

2019-03-09 20:47 UTC, xingweitian commented on homepage.html
> +                "</td>";
why add a blank here?

2019-03-11 18:06 UTC, zhangjiangqige approved these changes

2019-03-11 18:06 UTC, xingweitian approved these changes

2019-03-11 18:06 UTC, merged