Feature/travis
new-airbnb/kitchen-towel pull request #31
Opened 2019-03-18 22:04 UTC by lyuboxin

Resolved #25 implement automated tests for login page by travis

2019-03-18 22:11 UTC, zhangjiangqige submitted a review, later dismissed

2019-03-18 22:26 UTC, xingweitian requested changes

2019-03-18 22:26 UTC, xingweitian commented on test.sh
> +python test.py
add a new line at the end of the file

2019-03-18 22:26 UTC, xingweitian commented on test.py
> +
make this file meets PEP8

2019-03-18 22:26 UTC, xingweitian commented on test.py
> +testLogin("no username",'','','please enter your email')
choice one of them, ' or "

2019-03-18 22:26 UTC, xingweitian commented on test.py
> +GBK = "gbk"
we don't need to indicate gbk or utf8

2019-03-18 22:26 UTC, xingweitian commented on test.py
> +    # print '---------------------'
remove this line

2019-03-18 22:37 UTC, xingweitian requested changes

2019-03-18 22:37 UTC, xingweitian commented on test.py
> +CLOASE_AFTER_TEST =False
please meet PEP8

2019-03-19 02:40 UTC, xingweitian requested changes

2019-03-19 02:40 UTC, xingweitian commented on test.py
> +output('test page:' + browser.title)
use print, not output

2019-03-19 02:40 UTC, xingweitian commented on test.py
> +    browser.quit()
add a new line at the end of the file

2019-03-19 17:45 UTC, zhangjiangqige approved these changes
While it works for now, we need to be careful that sometimes the page need to be refreshed so the fields filled in previous test cases will not affect later cases.

2019-03-19 17:49 UTC, xingweitian approved these changes

2019-03-19 17:49 UTC, merged