modify the pattern of home page
new-airbnb/kitchen-towel pull request #53
Opened 2019-03-26 18:58 UTC by ericqiangguo

hi boss zhang, xing and lv, I have changed the layout of home page. Please give me your comments.

2019-03-26 21:46 UTC, xingweitian commented
I think #50, #56, #58 and #60 are not resolved

2019-03-26 21:47 UTC, xingweitian requested changes
see it in my comment.

2019-03-28 20:06 UTC, xingweitian commented
please remove "add room" from add_room.html, then there are no more questions for me.

2019-03-29 14:31 UTC, zhangjiangqige approved these changes

2019-03-30 20:15 UTC, merged